
syntax = "proto3";

option csharp_namespace = "UserServiceClient";

package Student;

import "google/protobuf/wrappers.proto";
import "ExternalServices/UserService/Protos/shared.proto";

service StudentService{
  rpc GetStudentById(GetStudentByIdRequest) returns (StudentModel);
}

message StudentModel{
  string Id = 1;
  string SsoId = 2;
  string FirstName = 3;
  string LastName = 4;
  google.protobuf.StringValue PatronymicName = 5;
  int32  GroupId = 6;
  google.protobuf.StringValue DroppedOutAt = 7;
  bool IsDeleted = 9;
}

message GetStudentByIdRequest{
  string Id = 1;
}